# Generated by Django 2.2.1 on 2019-06-22 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0003_caritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10, verbose_name='总价格')),
                ('staff', models.CharField(max_length=100, verbose_name='商品')),
                ('order_date', models.DateField(auto_now=True, verbose_name='订单时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_shop.User', verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_shop.Goods', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_shop.Order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单条目',
                'verbose_name_plural': '订单条目',
            },
        ),
    ]
